### PR TITLE
Added power support 

### PR DESCRIPTION
**Pull request by dthadi3**
Thanks for your code. Its working good.

Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

### CODE REVIEW

**Comment by dthadi3** [comment]
Hi @pataquets 
Can you please respond to this PR, waiting for your reply.

**Comment by pataquets** [comment]
I think you're talking to the wrong person, @dthadi3. I'm not the project maintainer/owner.

**Comment by johang** [comment]
I don't like it. You're duplicating the build matrix.

Just add this instead to achieve the same thing:

```
arch:
  - amd64
  - ppc64le
```

**Comment by dthadi3** [comment]
Thanks for your response @pataquets & @johang 

@johang The code you have given will work only for builds without Matrix code, I'm sharing you Travis documented example

jobs:
  include:
   - os: linux
     arch: ppc64le
   - os: linux
     arch: s390x

https://docs.travis-ci.com/user/multi-cpu-architectures#example-multi-architecture-build-matrix

**Comment by johang** [comment]
I see your point. The problem seems to be "matrix: include:"

However, I think someting like this should work:

```
language: cpp
os: linux
dist: focal
arch:
  - amd64
  - ppc64le
env:
  global:
    - MAKEFLAGS=-j2
    - PKG_CONFIG_PATH=/tmp/lib/pkgconfig
    - LD_LIBRARY_PATH=/tmp/lib
  jobs:
    - LIBTORRENT_BRANCH=RC_1_1
    - LIBTORRENT_BRANCH=RC_1_2
    - LIBTORRENT_BRANCH=RC_2_0
...
```

Basically removing "matrix: include:" and breaking out "os", "dist" to top level and moving "env" to "env: jobs:".

**Comment by dthadi3** [comment]
got your point now, modified the code without "matrix: include" and breaking out "os" and "dist" and moved "env" to "env: jobs".
and squashed the commits too. Thanks!

**Comment by johang** [comment]
I merged it. Thanks!

**Pull request merged**
