### PR TITLE
Fix OS X support.

### PR DESCRIPTION
**Pull request by greenboxal**
For some reason there was a `signal` symbol in OS X which isn't present on Linux build.

Also OS X pthreads doesn't support `pthread_setname_np` on any thread, just the current one.

Now it builds and works correctly. I installed osxfuse and successfully opened a torrent.

### CODE REVIEW

**Comment by johang** [comment]
Nice. Do you have instructions on how to build for OS X somewhere?

**Comment by greenboxal** [comment]
It was pretty straightforward, dependencies can be installed with:

```
brew install Caskroom/cask/osxfuse 
brew install libtorrent-rasterbar
```

The only problem I had was with libfuse version, it seems that the pkgconfig for libfuse that comes with OSXFuse 2.8 states that it is 2.7, I changed it manually and worked fine.

Besides this, the build was exactly as for Linux.

**Comment by Ivshti** [comment]
@greenboxal where is the pkgconfig for osxfuse? What exactly has to be changed?

I tried installing osxfuse and libtorrent-rasterbar yesterday but configure couldn't find fuse, I assume this is the same problem.

**Comment by greenboxal** [comment]
Mine was at `/usr/local/lib/pkgconfig/fuse.pc`, just changed it version(2.7.3 i think), to 2.8.2.

**Comment by johang** [comment]
If someone sends a pull request with `brew` steps added to readme I'll merge it.

**Comment by cprecioso** [comment]
I've added them in #24. Also, I'm looking at adding `btfs` directly to `brew` (Homebrew/homebrew-fuse#32).

**Pull request merged**
